import type { Config } from "tailwindcss";
import plugin from "tailwindcss/plugin";

/** View-transition fades + card-modal header stacking (formerly in tailwind.config.css). */
const dafGlobalStyles = plugin(({ addBase }) => {
  addBase({
    "@media (prefers-reduced-motion: no-preference)": {
      "@view-transition": {
        navigation: "auto",
      },
      "::view-transition-old(main-content)": {
        animation: "route-fade-out 0.12s ease forwards",
      },
      "::view-transition-new(main-content)": {
        animation: "route-fade-in 0.12s ease forwards",
      },
      "::view-transition-old(site-header)": {
        animation: "none",
      },
      "::view-transition-new(site-header)": {
        animation: "none",
      },
    },
    "body.card-modal-open header[role='banner']": {
      zIndex: "1",
    },
  });
});

/**
 * DaF design tokens — single source of truth for custom utilities and global base styles.
 */
const config = {
  plugins: [dafGlobalStyles],
  theme: {    extend: {
      fontFamily: {
        sans: ['Calibri', '"Segoe UI"', "Roboto", "sans-serif"],
        farsi: [
          '"Segoe UI"',
          "Tahoma",
          '"Noto Naskh Arabic"',
          '"Arial Unicode MS"',
          "sans-serif",
        ],
      },
      maxWidth: {
        site: "44rem",
        grammar: "48rem",
        tags: "52rem",
        auth: "22rem",
        "modal-sm": "26rem",
        "modal-md": "36rem",
      },
      colors: {
        daf: {
          blue: "rgb(48 96 140)",
          "gray-en": "rgb(64 64 64)",
          head: "rgb(47 111 184)",
          "head-dark": "rgb(38 92 158)",
          "head-hover": "#2860a8",
          "head-link": "#245a9c",
          "head-active": "#1a4a85",
          "head-soft": "#eef4fc",
          "head-softer": "#f4f8fc",
          "head-panel": "#f1f6fc",
          "head-tint": "#e8f0fa",
          "head-glow": "#4a8fd4",
          "head-pale": "#dceefb",
          "head-line": "#b8c9de",
          border: "#e0e0e0",
          "border-input": "#d8e2ef",
          "border-control": "#d8d8d8",
          "border-muted": "#ddd",
          "border-row": "#eee",
          "border-table": "#e2e8f0",
          "border-nav": "#e8edf3",
          "border-badge": "#c5d9ef",
          "border-badge-soft": "#c8d8ea",
          "border-danger-soft": "#e8c8c8",
          "border-import": "#c8dcc4",
          surface: "#fafafa",
          panel: "#fafafa",
          "panel-alt": "#f5f5f5",
          "panel-soft": "#f8fafc",
          "panel-muted": "#fafbfd",
          "panel-warm": "#fffef9",
          white: "#ffffff",
          ink: "#111111",
          text: "#222222",
          label: "#333333",
          body: "#444444",
          subtle: "#555555",
          muted: "#666666",
          faint: "#777777",
          hint: "#888888",
          disabled: "#999999",
          placeholder: "#b0b5bf",
          "icon-muted": "#b8bcc4",
          "nav-link": "#2b64b8",
          "nav-active": "#1a4f99",
          "nav-hover-bg": "#f4f8fd",
          "nav-btn-bg": "#f8fafc",
          "nav-toggle-bg": "#fafbfd",
          "nav-toggle-border": "#c5d5ea",
          "nav-toggle-active-border": "#b8cce8",
          "nav-backdrop": "rgba(18, 32, 52, 0.35)",
          "import-text": "#1a3d6b",
          "import-done": "#4a6748",
          "import-bg": "#f5f9fd",
          "import-done-bg": "#f4f8f3",
          "import-hover": "#eaf2fa",
          "import-done-hover": "#eaf4e8",
          "import-border-done": "#b5d4b0",
          danger: "#b00020",
          "danger-alt": "#b42318",
          "danger-strong": "#9f2b1a",
          "danger-hover": "#8a2416",
          "danger-text": "#8b2e2e",
          "danger-btn": "#a33",
          "danger-bg": "#fff8f7",
          "danger-bg-hover": "#fef0ee",
          "danger-border": "#f0d0cb",
          "danger-border-hover": "#e8b4ad",
          "danger-border-focus": "#d99a92",
          "danger-card-bg": "#fdf5f5",
          "danger-list-bg": "#fff8f8",
          "studied": "#5a9e38",
          "studied-border": "#4a8a28",
          "studied-text": "#6a8f55",
          "studied-hover": "#5f8f42",
          "studied-hover-border": "#8fb86e",
          "studied-bg": "#fafcf8",
          "studied-hover-bg": "#f4faf0",
          "studied-border-soft": "#c8dcc0",
          community: "#5a7a9a",
          "community-bg": "#f0f4f8",
          "community-border": "#d0dce8",
          customized: "#6a5a2f",
          "customized-bg": "#faf6ee",
          "customized-border": "#e8dcc0",
          notes: "#404040",
          skeleton: "#e4e8ec",
          footer: "#ececec",
          "ai-text": "#3d5a8a",
          "ai-from": "#f8fbff",
          "ai-to": "#eef4fc",
          "ai-hover-from": "#eef5ff",
          "ai-hover-to": "#e3eef9",
          "list-manage": "#f7fafd",
          "list-danger": "#a33",
          "badge-system-bg": "#eef4fc",
        },
        grm: {
          der: "#2f6fb8",
          "der-bg": "#e8f2fc",
          "der-border": "#a8c8e8",
          "der-light": "#5c9fd4",
          "der-text": "#1e4a7a",
          "der-text-dark": "#2a4a6a",
          das: "#2d7a52",
          "das-bg": "#e6f5ec",
          "das-border": "#9fd4b0",
          "das-light": "#5cb88a",
          "das-text": "#2a4a38",
          die: "#b83d6e",
          "die-bg": "#fce8f0",
          "die-border": "#e8a8c4",
          "die-light": "#d47aa0",
          "die-text": "#5a2a42",
          pl: "#5c4a9e",
          "pl-bg": "#ede8fc",
          "pl-border": "#c4b8e8",
          "pl-light": "#8a7ac4",
          "pl-text": "#3d3268",
          gold: "#c9921a",
          "gold-bg": "#fff8e6",
          "gold-border": "#ecd89a",
          "gold-text": "#5c4a18",
          "gold-title": "#8a6918",
          teal: "#1a7a72",
          "teal-bg": "#e6f7f5",
          "teal-border": "#9fd9d4",
          "teal-text": "#1a4a45",
          "teal-text-alt": "#1a5a54",
          slate: "#3d4a57",
          "slate-muted": "#5a6573",
          "slate-heading": "#1e3a5f",
          "slate-title": "#1a2332",
          "slate-body": "#2f3d4d",
          "slate-case": "#2f4f6f",
          "slate-meta": "#6b7a8a",
          "slate-plus": "#8a96a3",
          "slate-arrow": "#9aa3ad",
          "slate-label": "#7a8794",
          "slate-chip": "#4a5564",
          farsi: "#4a3d32",
          "farsi-note": "#6a5a40",
          notebook: "#fffef9",
          "notebook-line": "#d8dce2",
          "notebook-rule": "rgba(47, 111, 184, 0.07)",
          legend: "rgba(255, 248, 230, 0.85)",
          "legend-accent": "#e8c84a",
          hub: "#5a7a9e",
          "hub-border": "#d4e4f4",
          "hub-card-border": "#dce4ee",
          "hub-card-hover": "#a8c4e8",
          "hub-accent": "#f3e8fc",
          "hub-soon": "#f9fafb",
          panel: "#fafbfd",
          "panel-border": "#d8e4f0",
          "panel-border-soft": "#e8edf3",
          "panel-border-row": "#e8eef5",
          "panel-border-section": "#e8f0f8",
          "panel-chip": "#e2e8f0",
          "panel-table": "#f4f8fc",
          "panel-row": "#eef2f7",
          "panel-gold": "#b8860b",
          "panel-gold-text": "#6b4f12",
          speak: "#eef4fb",
          formula: "#1e3a5f",
          "formula-text": "#e8f2fc",
          toc: "#d0e0f0",
          "toc-hover": "#dce8f4",
        },
        toast: {
          success: "#1a4a2e",
          "success-bg": "#e6f5ec",
          "success-border": "#9fd4b0",
          error: "#6b1a1a",
          "error-bg": "#fce8e8",
          "error-border": "#e8a8a8",
          info: "#1e3a5f",
          "info-bg": "#e8f2fc",
          "info-border": "#a8c8e8",
        },
      },
      boxShadow: {
        "daf-focus-sm": "0 0 0 2px rgba(47, 111, 184, 0.12)",
        "daf-focus": "0 0 0 3px rgba(47, 111, 184, 0.18)",
        "daf-focus-lg": "0 0 0 3px rgba(47, 111, 184, 0.22)",
        "daf-inset-active":
          "inset 0 0 0 1px rgba(47, 111, 184, 0.14)",
        "daf-ring": "0 0 0 2px rgba(47, 111, 184, 0.12)",
        "daf-ring-image": "0 0 0 2px rgba(47, 111, 184, 0.12)",
        "danger-focus": "0 0 0 3px rgba(180, 35, 24, 0.14)",
        "studied-focus": "0 0 0 2px rgba(74, 138, 40, 0.45)",
        card: "0 1px 2px rgb(0 0 0 / 4%)",
        "card-md": "0 2px 12px rgba(0, 0, 0, 0.06)",
        modal: "0 8px 32px rgba(0, 0, 0, 0.12)",
        "modal-lg": "0 8px 40px rgba(0, 0, 0, 0.14)",
        dropdown: "0 4px 12px rgba(0, 0, 0, 0.08)",
        toast: "0 4px 16px rgba(0, 0, 0, 0.12)",
        chip: "0 1px 2px rgba(0, 0, 0, 0.04)",
        section: "0 2px 10px rgba(0, 0, 0, 0.03)",
        grammar: "0 1px 3px rgba(30, 58, 95, 0.06)",
        "grammar-card": "0 1px 4px rgba(0, 0, 0, 0.04)",
        hub: "0 4px 18px rgba(47, 111, 184, 0.08)",
        "hub-card": "0 8px 22px rgba(47, 111, 184, 0.14)",
        "hub-card-bar": "0 2px 6px rgba(47, 111, 184, 0.25)",
        nav: "0 1px 0 rgba(0, 0, 0, 0.04)",
        "nav-menu": "0 10px 24px rgba(15, 35, 60, 0.12)",
        lightbox: "0 8px 32px rgba(0, 0, 0, 0.35)",
      },
      backgroundImage: {
        "daf-select-chevron":
          "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath fill='%23555' d='M2.5 4.5 6 8l3.5-3.5'/%3E%3C/svg%3E\")",
        "grammar-hub":
          "linear-gradient(135deg, var(--color-grm-der-bg) 0%, var(--color-grm-hub-accent) 45%, var(--color-grm-das-bg) 100%)",
        "grammar-lead":
          "linear-gradient(to right, var(--color-grm-der-bg), transparent)",
        "grammar-number":
          "linear-gradient(to bottom right, var(--color-daf-head), var(--color-grm-der-light))",
        "grammar-aus":
          "linear-gradient(180deg, var(--color-grm-teal-bg), var(--color-daf-white))",
        "grammar-travel-nach":
          "linear-gradient(180deg, var(--color-grm-das-bg), var(--color-daf-white))",
        "grammar-travel-in":
          "linear-gradient(180deg, var(--color-grm-der-bg), var(--color-daf-white))",
        "grammar-ai":
          "linear-gradient(180deg, var(--color-daf-ai-from) 0%, var(--color-daf-ai-to) 100%)",
        "grammar-ai-hover":
          "linear-gradient(180deg, var(--color-daf-ai-hover-from) 0%, var(--color-daf-ai-hover-to) 100%)",
        "grammar-notebook":
          "repeating-linear-gradient(180deg, transparent, transparent 1.35rem, var(--color-grm-notebook-rule) 1.35rem, var(--color-grm-notebook-rule) calc(1.35rem + 1px))",
      },
      keyframes: {
        "deck-shimmer": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "0.75" },
        },
        "route-fade-out": {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        "route-fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
      },
      animation: {
        "deck-shimmer": "deck-shimmer 1.5s ease-in-out infinite",
      },
    },
  },
} satisfies Config;

export default config;
