import type { Config } from "tailwindcss";
import plugin from "tailwindcss/plugin";

/** View-transition fades + card-modal header stacking (formerly in tailwind.config.css). */
const dafGlobalStyles = plugin(({ addBase }) => {
  addBase({
    "@media (prefers-reduced-motion: no-preference)": {
      "@view-transition": {
        navigation: "auto",
      },
      "::view-transition-old(main-content)": {
        animation: "route-fade-out 0.12s ease forwards",
      },
      "::view-transition-new(main-content)": {
        animation: "route-fade-in 0.12s ease forwards",
      },
      "::view-transition-old(site-header)": {
        animation: "none",
      },
      "::view-transition-new(site-header)": {
        animation: "none",
      },
    },
    "body.card-modal-open header[role='banner']": {
      zIndex: "1",
    },
  });
});

/**
 * DaF design tokens — single source of truth for custom utilities and global base styles.
 * All color values reference CSS custom properties defined in app/tailwind.css
 * so that dark mode (.dark class) works automatically across all components.
 */
const config = {
  darkMode: "class",
  plugins: [dafGlobalStyles],
  theme: {    extend: {
      fontFamily: {
        sans: ['Calibri', '"Segoe UI"', "Roboto", "sans-serif"],
        farsi: [
          '"Segoe UI"',
          "Tahoma",
          '"Noto Naskh Arabic"',
          '"Arial Unicode MS"',
          "sans-serif",
        ],
      },
      maxWidth: {
        site: "44rem",
        grammar: "48rem",
        tags: "52rem",
        auth: "22rem",
        "modal-sm": "26rem",
        "modal-md": "36rem",
      },
      colors: {
        daf: {
          "blue": "var(--color-daf-blue)",
          "gray-en": "var(--color-daf-gray-en)",
          "head": "var(--color-daf-head)",
          "head-dark": "var(--color-daf-head-dark)",
          "head-hover": "var(--color-daf-head-hover)",
          "head-link": "var(--color-daf-head-link)",
          "head-active": "var(--color-daf-head-active)",
          "head-soft": "var(--color-daf-head-soft)",
          "head-softer": "var(--color-daf-head-softer)",
          "head-panel": "var(--color-daf-head-panel)",
          "head-tint": "var(--color-daf-head-tint)",
          "head-glow": "var(--color-daf-head-glow)",
          "head-pale": "var(--color-daf-head-pale)",
          "head-line": "var(--color-daf-head-line)",
          "border": "var(--color-daf-border)",
          "border-input": "var(--color-daf-border-input)",
          "border-control": "var(--color-daf-border-control)",
          "border-muted": "var(--color-daf-border-muted)",
          "border-row": "var(--color-daf-border-row)",
          "border-table": "var(--color-daf-border-table)",
          "border-nav": "var(--color-daf-border-nav)",
          "border-badge": "var(--color-daf-border-badge)",
          "border-badge-soft": "var(--color-daf-border-badge-soft)",
          "border-danger-soft": "var(--color-daf-border-danger-soft)",
          "border-import": "var(--color-daf-border-import)",
          "surface": "var(--color-daf-surface)",
          "panel": "var(--color-daf-panel)",
          "panel-alt": "var(--color-daf-panel-alt)",
          "panel-soft": "var(--color-daf-panel-soft)",
          "panel-muted": "var(--color-daf-panel-muted)",
          "panel-warm": "var(--color-daf-panel-warm)",
          "white": "var(--color-daf-white)",
          "ink": "var(--color-daf-ink)",
          "text": "var(--color-daf-text)",
          "label": "var(--color-daf-label)",
          "body": "var(--color-daf-body)",
          "subtle": "var(--color-daf-subtle)",
          "muted": "var(--color-daf-muted)",
          "faint": "var(--color-daf-faint)",
          "hint": "var(--color-daf-hint)",
          "disabled": "var(--color-daf-disabled)",
          "placeholder": "var(--color-daf-placeholder)",
          "icon-muted": "var(--color-daf-icon-muted)",
          "nav-link": "var(--color-daf-nav-link)",
          "nav-active": "var(--color-daf-nav-active)",
          "nav-hover-bg": "var(--color-daf-nav-hover-bg)",
          "nav-btn-bg": "var(--color-daf-nav-btn-bg)",
          "nav-toggle-bg": "var(--color-daf-nav-toggle-bg)",
          "nav-toggle-border": "var(--color-daf-nav-toggle-border)",
          "nav-toggle-active-border": "var(--color-daf-nav-toggle-active-border)",
          "nav-backdrop": "var(--color-daf-nav-backdrop)",
          "import-text": "var(--color-daf-import-text)",
          "import-done": "var(--color-daf-import-done)",
          "import-bg": "var(--color-daf-import-bg)",
          "import-done-bg": "var(--color-daf-import-done-bg)",
          "import-hover": "var(--color-daf-import-hover)",
          "import-done-hover": "var(--color-daf-import-done-hover)",
          "import-border-done": "var(--color-daf-import-border-done)",
          "danger": "var(--color-daf-danger)",
          "danger-alt": "var(--color-daf-danger-alt)",
          "danger-strong": "var(--color-daf-danger-strong)",
          "danger-hover": "var(--color-daf-danger-hover)",
          "danger-text": "var(--color-daf-danger-text)",
          "danger-btn": "var(--color-daf-danger-btn)",
          "danger-bg": "var(--color-daf-danger-bg)",
          "danger-bg-hover": "var(--color-daf-danger-bg-hover)",
          "danger-border": "var(--color-daf-danger-border)",
          "danger-border-hover": "var(--color-daf-danger-border-hover)",
          "danger-border-focus": "var(--color-daf-danger-border-focus)",
          "danger-card-bg": "var(--color-daf-danger-card-bg)",
          "danger-list-bg": "var(--color-daf-danger-list-bg)",
          "studied": "var(--color-daf-studied)",
          "studied-border": "var(--color-daf-studied-border)",
          "studied-text": "var(--color-daf-studied-text)",
          "studied-hover": "var(--color-daf-studied-hover)",
          "studied-hover-border": "var(--color-daf-studied-hover-border)",
          "studied-bg": "var(--color-daf-studied-bg)",
          "studied-hover-bg": "var(--color-daf-studied-hover-bg)",
          "studied-border-soft": "var(--color-daf-studied-border-soft)",
          "community": "var(--color-daf-community)",
          "community-bg": "var(--color-daf-community-bg)",
          "community-border": "var(--color-daf-community-border)",
          "customized": "var(--color-daf-customized)",
          "customized-bg": "var(--color-daf-customized-bg)",
          "customized-border": "var(--color-daf-customized-border)",
          "notes": "var(--color-daf-notes)",
          "skeleton": "var(--color-daf-skeleton)",
          "footer": "var(--color-daf-footer)",
          "ai-text": "var(--color-daf-ai-text)",
          "ai-from": "var(--color-daf-ai-from)",
          "ai-to": "var(--color-daf-ai-to)",
          "ai-hover-from": "var(--color-daf-ai-hover-from)",
          "ai-hover-to": "var(--color-daf-ai-hover-to)",
          "list-manage": "var(--color-daf-list-manage)",
          "list-danger": "var(--color-daf-list-danger)",
          "badge-system-bg": "var(--color-daf-badge-system-bg)",
        },
        grm: {
          "der": "var(--color-grm-der)",
          "der-bg": "var(--color-grm-der-bg)",
          "der-border": "var(--color-grm-der-border)",
          "der-light": "var(--color-grm-der-light)",
          "der-text": "var(--color-grm-der-text)",
          "der-text-dark": "var(--color-grm-der-text-dark)",
          "das": "var(--color-grm-das)",
          "das-bg": "var(--color-grm-das-bg)",
          "das-border": "var(--color-grm-das-border)",
          "das-light": "var(--color-grm-das-light)",
          "das-text": "var(--color-grm-das-text)",
          "die": "var(--color-grm-die)",
          "die-bg": "var(--color-grm-die-bg)",
          "die-border": "var(--color-grm-die-border)",
          "die-light": "var(--color-grm-die-light)",
          "die-text": "var(--color-grm-die-text)",
          "pl": "var(--color-grm-pl)",
          "pl-bg": "var(--color-grm-pl-bg)",
          "pl-border": "var(--color-grm-pl-border)",
          "pl-light": "var(--color-grm-pl-light)",
          "pl-text": "var(--color-grm-pl-text)",
          "gold": "var(--color-grm-gold)",
          "gold-bg": "var(--color-grm-gold-bg)",
          "gold-border": "var(--color-grm-gold-border)",
          "gold-text": "var(--color-grm-gold-text)",
          "gold-title": "var(--color-grm-gold-title)",
          "teal": "var(--color-grm-teal)",
          "teal-bg": "var(--color-grm-teal-bg)",
          "teal-border": "var(--color-grm-teal-border)",
          "teal-text": "var(--color-grm-teal-text)",
          "teal-text-alt": "var(--color-grm-teal-text-alt)",
          "slate": "var(--color-grm-slate)",
          "slate-muted": "var(--color-grm-slate-muted)",
          "slate-heading": "var(--color-grm-slate-heading)",
          "slate-title": "var(--color-grm-slate-title)",
          "slate-body": "var(--color-grm-slate-body)",
          "slate-case": "var(--color-grm-slate-case)",
          "slate-meta": "var(--color-grm-slate-meta)",
          "slate-plus": "var(--color-grm-slate-plus)",
          "slate-arrow": "var(--color-grm-slate-arrow)",
          "slate-label": "var(--color-grm-slate-label)",
          "slate-chip": "var(--color-grm-slate-chip)",
          "farsi": "var(--color-grm-farsi)",
          "farsi-note": "var(--color-grm-farsi-note)",
          "notebook": "var(--color-grm-notebook)",
          "notebook-line": "var(--color-grm-notebook-line)",
          "notebook-rule": "var(--color-grm-notebook-rule)",
          "legend": "var(--color-grm-legend)",
          "legend-accent": "var(--color-grm-legend-accent)",
          "hub": "var(--color-grm-hub)",
          "hub-border": "var(--color-grm-hub-border)",
          "hub-card-border": "var(--color-grm-hub-card-border)",
          "hub-card-hover": "var(--color-grm-hub-card-hover)",
          "hub-accent": "var(--color-grm-hub-accent)",
          "hub-soon": "var(--color-grm-hub-soon)",
          "panel": "var(--color-grm-panel)",
          "panel-border": "var(--color-grm-panel-border)",
          "panel-border-soft": "var(--color-grm-panel-border-soft)",
          "panel-border-row": "var(--color-grm-panel-border-row)",
          "panel-border-section": "var(--color-grm-panel-border-section)",
          "panel-chip": "var(--color-grm-panel-chip)",
          "panel-table": "var(--color-grm-panel-table)",
          "panel-row": "var(--color-grm-panel-row)",
          "panel-gold": "var(--color-grm-panel-gold)",
          "panel-gold-text": "var(--color-grm-panel-gold-text)",
          "speak": "var(--color-grm-speak)",
          "formula": "var(--color-grm-formula)",
          "formula-text": "var(--color-grm-formula-text)",
          "toc": "var(--color-grm-toc)",
          "toc-hover": "var(--color-grm-toc-hover)",
        },
        toast: {
          "success": "var(--color-toast-success)",
          "success-bg": "var(--color-toast-success-bg)",
          "success-border": "var(--color-toast-success-border)",
          "error": "var(--color-toast-error)",
          "error-bg": "var(--color-toast-error-bg)",
          "error-border": "var(--color-toast-error-border)",
          "info": "var(--color-toast-info)",
          "info-bg": "var(--color-toast-info-bg)",
          "info-border": "var(--color-toast-info-border)",
        },
      },
      boxShadow: {
        "daf-focus-sm": "0 0 0 2px rgba(47, 111, 184, 0.12)",
        "daf-focus": "0 0 0 3px rgba(47, 111, 184, 0.18)",
        "daf-focus-lg": "0 0 0 3px rgba(47, 111, 184, 0.22)",
        "daf-inset-active":
          "inset 0 0 0 1px rgba(47, 111, 184, 0.14)",
        "daf-ring": "0 0 0 2px rgba(47, 111, 184, 0.12)",
        "daf-ring-image": "0 0 0 2px rgba(47, 111, 184, 0.12)",
        "danger-focus": "0 0 0 3px rgba(180, 35, 24, 0.14)",
        "studied-focus": "0 0 0 2px rgba(74, 138, 40, 0.45)",
        card: "0 1px 2px rgb(0 0 0 / 4%)",
        "card-md": "0 2px 12px rgba(0, 0, 0, 0.06)",
        modal: "0 8px 32px rgba(0, 0, 0, 0.12)",
        "modal-lg": "0 8px 40px rgba(0, 0, 0, 0.14)",
        dropdown: "0 4px 12px rgba(0, 0, 0, 0.08)",
        toast: "0 4px 16px rgba(0, 0, 0, 0.12)",
        chip: "0 1px 2px rgba(0, 0, 0, 0.04)",
        section: "0 2px 10px rgba(0, 0, 0, 0.03)",
        grammar: "0 1px 3px rgba(30, 58, 95, 0.06)",
        "grammar-card": "0 1px 4px rgba(0, 0, 0, 0.04)",
        hub: "0 4px 18px rgba(47, 111, 184, 0.08)",
        "hub-card": "0 8px 22px rgba(47, 111, 184, 0.14)",
        "hub-card-bar": "0 2px 6px rgba(47, 111, 184, 0.25)",
        nav: "0 1px 0 rgba(0, 0, 0, 0.04)",
        "nav-menu": "0 10px 24px rgba(15, 35, 60, 0.12)",
        lightbox: "0 8px 32px rgba(0, 0, 0, 0.35)",
      },
      backgroundImage: {
        "daf-select-chevron":
          "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath fill='%23555' d='M2.5 4.5 6 8l3.5-3.5'/%3E%3C/svg%3E\")",
        "grammar-hub":
          "linear-gradient(135deg, var(--color-grm-der-bg) 0%, var(--color-grm-hub-accent) 45%, var(--color-grm-das-bg) 100%)",
        "grammar-lead":
          "linear-gradient(to right, var(--color-grm-der-bg), transparent)",
        "grammar-number":
          "linear-gradient(to bottom right, var(--color-daf-head), var(--color-grm-der-light))",
        "grammar-aus":
          "linear-gradient(180deg, var(--color-grm-teal-bg), var(--color-daf-white))",
        "grammar-travel-nach":
          "linear-gradient(180deg, var(--color-grm-das-bg), var(--color-daf-white))",
        "grammar-travel-in":
          "linear-gradient(180deg, var(--color-grm-der-bg), var(--color-daf-white))",
        "grammar-ai":
          "linear-gradient(180deg, var(--color-daf-ai-from) 0%, var(--color-daf-ai-to) 100%)",
        "grammar-ai-hover":
          "linear-gradient(180deg, var(--color-daf-ai-hover-from) 0%, var(--color-daf-ai-hover-to) 100%)",
        "grammar-notebook":
          "repeating-linear-gradient(180deg, transparent, transparent 1.35rem, var(--color-grm-notebook-rule) 1.35rem, var(--color-grm-notebook-rule) calc(1.35rem + 1px))",
      },
      keyframes: {
        "deck-shimmer": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "0.75" },
        },
        "route-fade-out": {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        "route-fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
      },
      animation: {
        "deck-shimmer": "deck-shimmer 1.5s ease-in-out infinite",
      },
    },
  },
} satisfies Config;

export default config;
